---

host_keyfile: ~/ssh/ssh_host_ecdsa_key.pub
root_keyfile: /home/{{ ssh_user }}/.ssh/id_ecdsa
tmp_keyfile: "./tmp/id_ecdsa.{{ inventory_hostname }}"
tmp_host_keyfile: "./tmp/host_ecdsa.{{ inventory_hostname }}"
